# Generated by Django 6.0 on 2026-01-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ravitaillement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_plein', models.DateTimeField(db_comment='Date et heure du ravitaillement')),
                ('kilometrage', models.IntegerField(db_comment='Kilométrage au moment du plein')),
                ('quantite_litres', models.DecimalField(db_column='quantite', db_comment='Quantité en Litres', decimal_places=2, max_digits=8)),
                ('prix_unitaire', models.DecimalField(db_comment='Prix du litre', decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ravitaillement',
                'verbose_name_plural': 'Ravitaillements',
                'db_table': 'carburants',
                'managed': False,
            },
        ),
    ]
