# Generated by Django 6.0 on 2025-12-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Affectations',
                'db_table': 'affectations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('numero_permis', models.CharField(max_length=50, unique=True)),
                ('adresse', models.CharField(blank=True, db_comment='Adresse/quartier', max_length=255, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('tel1', models.CharField(blank=True, max_length=20, null=True)),
                ('tel2', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'conducteurs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'departements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(db_comment="Plaque d'immatriculation", max_length=50, unique=True)),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('couleur', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_serie', models.CharField(blank=True, db_comment='N* Série', max_length=150, null=True, unique=True)),
                ('date_mise_circulation', models.DateField(blank=True, db_comment='Année', null=True)),
                ('type_vehicule', models.CharField(blank=True, db_comment='4x4, berline, citadine, coupé, etc.', max_length=50, null=True)),
                ('type_carburant', models.CharField(blank=True, db_comment='essence, diesel, etc.', max_length=50, null=True)),
                ('kilometrage_initial', models.IntegerField(blank=True, db_comment='Kilométrage initial', null=True)),
                ('actif', models.IntegerField(blank=True, db_comment='Véhicule actif ou pas', null=True)),
                ('location_oui_non', models.IntegerField(blank=True, db_comment='Gestion des achats/location', null=True)),
                ('date_achat_location', models.DateField(blank=True, db_comment='date achat/location', null=True)),
                ('prix_achat_location', models.DecimalField(blank=True, db_comment='prix achat/location', decimal_places=2, max_digits=10, null=True)),
                ('expiration_garantie', models.DateField(blank=True, null=True)),
                ('prix_vente', models.DecimalField(blank=True, db_comment='prix vente (si revendu)', decimal_places=2, max_digits=10, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vehicules',
                'managed': False,
            },
        ),
    ]
