# Generated by Django 6.0 on 2026-01-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flotte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assurance', models.DateField(db_column='date_assurance')),
                ('expiration_assurance', models.DateField(db_column='expiration_assurance')),
                ('rappel_avant_jours', models.IntegerField(db_column='rappel_avant_jours')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Assurances',
                'db_table': 'assurances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaxeCirculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taxe_circulation', models.DateField(db_column='date_taxe_circulation')),
                ('expiration', models.DateField(db_column='expiration')),
                ('rappel_avant_jours', models.IntegerField(db_column='rappel_avant_jours')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Taxe de Circulation',
                'verbose_name_plural': 'Taxes de Circulation',
                'db_table': 'taxes_circulation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VisiteTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derniere_visite', models.DateField(db_column='derniere_visite')),
                ('prochaine_visite', models.DateField(db_column='prochaine_visite')),
                ('rappel_avant_jours', models.IntegerField(db_column='rappel_avant_jours')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Visite Technique',
                'verbose_name_plural': 'Visites Techniques',
                'db_table': 'visites_techniques',
                'managed': False,
            },
        ),
    ]
