# Generated by Django 6.0 on 2025-12-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type_activite', models.CharField(db_comment='vente vehicule, location vehicule, assureur, vente pièce auto, entretien, reparation, vente carburant', max_length=255)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('tel1', models.CharField(blank=True, max_length=20, null=True)),
                ('tel2', models.CharField(blank=True, max_length=20, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('site_web', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('type_fournisseur', models.CharField(blank=True, db_comment='Type (à affiner si nécessaire)', max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fournisseurs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constructeur', models.CharField(blank=True, db_comment='Constructeur de la pièce', max_length=150, null=True)),
                ('numero', models.CharField(db_comment='Numéro de la pièce', max_length=150)),
                ('nom', models.CharField(max_length=255)),
                ('prix', models.DecimalField(db_comment='Prix unitaire', decimal_places=2, max_digits=10)),
                ('date_prix', models.DateField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pieces',
                'managed': False,
            },
        ),
    ]
