# Generated by Django 6.0 on 2026-01-07 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flotte', '0002_assurance_taxecirculation_visitetechnique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationTrajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_depart', models.CharField(max_length=255)),
                ('point_arrivee', models.CharField(max_length=255)),
                ('distance_km', models.DecimalField(decimal_places=2, help_text='Distance estimée en kilomètres.', max_digits=8)),
                ('duree_minutes', models.PositiveIntegerField(help_text='Durée estimée en minutes.')),
                ('consommation_moyenne_l_100', models.DecimalField(decimal_places=2, default=8.0, help_text="Consommation moyenne (L/100 km) utilisée pour l'estimation.", max_digits=6)),
                ('cout_estime_carburant', models.DecimalField(blank=True, decimal_places=2, help_text='Coût estimé du carburant pour ce trajet.', max_digits=10, null=True)),
                ('date_simulation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, help_text='Utilisateur ayant lancé la simulation.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(blank=True, help_text='Véhicule utilisé pour la simulation (optionnel).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='flotte.vehicule')),
            ],
            options={
                'verbose_name': 'Simulation de trajet',
                'verbose_name_plural': 'Simulations de trajets',
                'ordering': ['-date_simulation'],
            },
        ),
    ]
