# Generated by Django 6.0 on 2025-12-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_destinataire', models.CharField(max_length=100)),
                ('type_alerte', models.CharField(db_comment='assurance, taxe circulation, entretient, visite technique', max_length=50)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Alertes E-mail',
                'db_table': 'alertes_email',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Anomalie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_anomalie', models.CharField(blank=True, db_comment='Mécanique, Accident, Autre', max_length=100, null=True)),
                ('description', models.TextField(db_comment='Formulaire simple pour signaler un problème')),
                ('statut', models.CharField(blank=True, db_comment='Signalé, En cours, Résolu', max_length=50, null=True)),
                ('date_declaration', models.DateTimeField(blank=True, null=True)),
                ('photo_path', models.CharField(blank=True, db_comment="Possibilité d'attacher des photos", max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'anomalies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assurance', models.DateField()),
                ('expiration_assurance', models.DateField()),
                ('rappel_avant_jours', models.IntegerField(db_comment='Rappel avant (jours)')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assurances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carburant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_plein', models.DateTimeField(db_comment='Date, Heure')),
                ('kilometrage', models.IntegerField(db_comment='Kilométrage au moment du plein')),
                ('quantite', models.DecimalField(db_comment='Quantité (Litres)', decimal_places=2, max_digits=8)),
                ('prix_unitaire', models.DecimalField(db_comment='Prix unitaire', decimal_places=3, max_digits=6)),
                ('station_service', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'carburants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, db_comment="Description de la dépense (Pièce, Main d'oeuvre, etc.)", max_length=255, null=True)),
                ('quantite', models.IntegerField()),
                ('cout_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Détail des Dépenses',
                'db_table': 'detail_depenses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(db_comment="Détail de l'entretien")),
                ('date_entretien', models.DateField(db_comment="Date de l'entretien")),
                ('kilometrage', models.IntegerField(db_comment="Kilométrage au moment de l'entretien")),
                ('note', models.TextField(blank=True, null=True)),
                ('depense_type', models.CharField(blank=True, db_comment='Ex: Vidange, Réparation', max_length=100, null=True)),
                ('cout_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entretiens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntretienMaitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('repeter_par_date', models.IntegerField(blank=True, db_comment='Répéter toutes (jours)', null=True)),
                ('repeter_par_kilometrage', models.IntegerField(blank=True, db_comment='Répéter au kilométrage (km)', null=True)),
                ('rappel_avant_jours', models.IntegerField(blank=True, db_comment='Rappel avant (jours)', null=True)),
                ('rappel_avant_kilometrage', models.IntegerField(blank=True, db_comment='Rappel avant (km)', null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entretien_maitres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaxeCirculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taxe_circulation', models.DateField()),
                ('expiration', models.DateField()),
                ('rappel_avant_jours', models.IntegerField(db_comment='Rappel avant (jours)')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Taxes de Circulation',
                'db_table': 'taxes_circulation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VisiteTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derniere_visite', models.DateField()),
                ('prochaine_visite', models.DateField()),
                ('rappel_avant_jours', models.IntegerField(db_comment='Rappel avant (jours)')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Visites Techniques',
                'db_table': 'visites_techniques',
                'managed': False,
            },
        ),
    ]
