# Generated by Django 6.0 on 2026-01-07 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flotte', '0002_assurance_taxecirculation_visitetechnique'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('assurance', 'Assurance'), ('visite_technique', 'Visite technique'), ('taxe', 'Taxe de circulation'), ('maintenance', 'Maintenance')], max_length=30)),
                ('message', models.CharField(max_length=255)),
                ('date_echeance', models.DateField()),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('est_resolue', models.BooleanField(default=False)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flotte.vehicule')),
            ],
        ),
    ]
