# Generated by Django 6.0 on 2026-01-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alertesysteme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlerteSysteme',
        ),
    ]
