"""
Django settings for FMS_Core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q%kzwg4=*#6^nr=^tv@)mv@*i!b=dg3@)==4r9=g6@36aq=i&f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["127.0.0.1",
                 "localhost",
                 "www.fms.ravisa.org",
                 "fms.ravisa.org",
                 ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'utilisateurs.apps.UtilisateursConfig',
    'flotte.apps.FlotteConfig',
    'maintenance.apps.MaintenanceConfig',
    'fournisseurs.apps.FournisseursConfig',
    'carburant.apps.CarburantConfig',
    'rapports.apps.RapportsConfig',

    # AJOUTEZ L'APPLICATION 'users' SI VOUS L'AVEZ RENOMMÉE EN 'utilisateurs'
    # Sinon, assurez-vous que le nom ici correspond à votre dossier d'application (e.g., 'users' ou 'utilisateurs')
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'FMS_Core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # AJOUT : Inclusion du dossier 'templates' à la racine du projet pour les templates de base
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'FMS_Core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'sc1koga4651_fms_prod',
        'USER': 'sc1koga4651_fms_user',
        'PASSWORD': 'Jesuisfms_user',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# ==========================================================
# PARAMÈTRES D'AUTHENTIFICATION PERSONNALISÉE
# ==========================================================

# Utilise le modèle 'User' de l'application 'utilisateurs'
AUTH_USER_MODEL = 'utilisateurs.User'

# CORRECTION FINALE : Utiliser le nom de l'URL 'login'
LOGIN_URL = 'login'

# Redirection après connexion réussie
LOGIN_REDIRECT_URL = 'dashboard'

# Redirection après déconnexion
# On pointe directement vers le nom d'URL qui gère la connexion, soit '/auth/login/'
LOGOUT_REDIRECT_URL = 'login' # <--- CORRECTION APPLIQUÉE ICI